Adjusted Outline
ohcnetwork/landing pull request #36
Opened 2024-12-07 08:16 UTC by nithish1018

Fixes #33 
Improved Outline Handling In Desktop and Mobile View

2024-12-11 05:53 UTC, shivankacker requested changes
I think it will be best if there was no outline at all.

2024-12-11 06:29 UTC, nithish1018 commented
Ok, I'll update the PR @shivankacker

2024-12-11 20:45 UTC, shivankacker approved these changes

2024-12-13 14:49 UTC, bodhish approved these changes

2024-12-13 14:49 UTC, merged