Fix: Contact link does not work properly in the footer
ohcnetwork/landing pull request #38
Opened 2024-12-10 17:53 UTC by AdityaJ2305

Fix: #20 
@shivankacker 

#Screen-Recording

2024-12-11 05:50 UTC, shivankacker approved these changes

2024-12-11 05:55 UTC, shivankacker requested changes
@AdityaJ2305 this should bring you to the home page, not the footer.

2024-12-11 06:45 UTC, AdityaJ2305 commented
> @AdityaJ2305 this should bring you to the home page, not the footer.

Ok, so we should remove the contact from header when we are already on home page ? I thought on footer we got GitHub yt slack links to get assistance and as per issue mentioned the bug was with scrolling

2024-12-11 20:44 UTC, shivankacker commented
@AdityaJ2305 the links stay the same. It will take you to the contact section of the home page. It is fine if it does not scroll for the time being

2024-12-11 20:54 UTC, AdityaJ2305 commented
> @AdityaJ2305 the links stay the same. It will take you to the contact section of the home page. It is fine if it does not scroll for the time being

ok, then it is working same this way on local not on main website 🤔

2024-12-12 07:18 UTC, AdityaJ2305 commented
> @AdityaJ2305 the links stay the same. It will take you to the contact section of the home page. It is fine if it does not scroll for the time being

@shivankacker, done with the changes.

2024-12-12 08:07 UTC, AdityaJ2305 commented
Hey @shivankacker, can we implement scrolling for the home page and direct redirects for the other pages?

2024-12-13 07:20 UTC, AdityaJ2305 commented
Hey @shivankacker , Could you review the changes ? and let me know changes required

2024-12-13 14:35 UTC, shivankacker commented
@AdityaJ2305 It is not taking me to the contact section when I am at another page.

2024-12-13 14:37 UTC, shivankacker requested changes
Please make the requested changes

2024-12-13 15:10 UTC, AdityaJ2305 commented
> Please make the requested changes

It’s working fine locally 🤔. However, I’ve made changes based on the comment below.





> Hey @shivankacker, can we implement scrolling for the home page and direct redirects for the other pages?

2024-12-13 15:12 UTC, AdityaJ2305 commented
Is the Netlify preview deployment getting updated or not? 😅

2024-12-15 06:24 UTC, AdityaJ2305 commented
Hey @shivankacker, it’s working fine on deployment now. However, we can adjust the setTimeout duration based on the desired user experience.

2024-12-15 07:04 UTC, AdityaJ2305 commented
Hey @shivankacker, it’s working fine on deployment now. However, we can adjust the setTimeout duration based on the desired user experience.

2024-12-16 12:32 UTC, shivankacker requested changes
@AdityaJ2305 the screen recording you shared is supposed to be the ideal solution, but cannot see it working on the deploy preview. I don't think there is an issue with the deploy preview though 🤔

https://github.com/user-attachments/assets/feabdb6a-0abc-4066-93d7-67c52a387ced

2024-12-24 15:32 UTC, shivankacker commented
@AdityaJ2305 any updates here?

2024-12-24 15:35 UTC, AdityaJ2305 commented
I’ll need to check it, or if I can’t solve it, I’ll ping the engineering team for help. I’ll try to resolve it ASAP

2025-01-04 13:43 UTC, closed without merging