Update Primary features images visibility
ohcnetwork/landing pull request #46
Opened 2024-12-31 15:14 UTC by Mahendar0701

Fixes : #45 

Previous:

![Image](https://github.com/user-attachments/assets/615121be-981c-4893-97e5-2fd655f930cd)

Updated:

![Image](https://github.com/user-attachments/assets/14e47986-cc13-491f-af40-0211dafa805e)

2025-01-10 09:52 UTC, shivankacker requested changes
@Mahendar0701 lgtm, can we move to `tsx`?

2025-01-10 10:15 UTC, Mahendar0701 commented
> > @Mahendar0701 lgtm, can we move to `tsx`?
> 
> @shivankacker
> 
> Yeah i will update and also bodhish suggested to add swiping feature for images in mobile view on slack [comment](https://rebuildearth.slack.com/archives/C010GQBMFJ9/p1736272506109419?thread_ts=1736272425.849779&cid=C010GQBMFJ9). Can i use `react-swipeable` library for that or will you recommend any other library?

2025-01-10 10:31 UTC, shivankacker commented
@Mahendar0701 no need for libraries, try `scroll-snap` 
https://tailwindcss.com/docs/scroll-snap-align

Scroll would auto change to swipe on mobile.

2025-01-14 14:45 UTC, merged

2025-01-29 15:27 UTC, Mahendar0701 commented
@rithviknishad can you please assign story points for this PR